name: run-tests
on:
  push:
    branches: main

jobs:
  gtest_parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install g++ gtest
        run: 
         sudo apt-get update && sudo apt-get install gcc g++ libgtest-dev -y --no-install-recommends
      - name: format check
        run:
          sudo apt install clang-format && find src include -regex ".*\\.\\(cpp\\|hpp\\|c\\|h\\)" | xargs clang-format -style=file --Werror --dry-run -i 

      - name: build
        run: 
          mkdir build && cd build && cmake .. && make

      - name: run test
        run:
          bin/gtest-parse
